name: Build wiki
on:
  push:
    branches:
      master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.TOKEN }}
    - name: Push to wiki
      env:
        TOKEN: ${{ secrets.TOKEN }}
      if: env.TOKEN != ''
      run: |
        git remote add upstream git@github.com:yt-dlp/yt-dlp.wiki
        git fetch upstream
        git push --force upstream master
